---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 5672, host: 5672}] 
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[chef-rabbit_mq::default]
    attributes:
